setwd('C:/Users/Gabriela/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/home/gabi/Projects/R-course')

full = read.csv('data.csv')

levels(full$Region)

br_global <- subset(full, full$Region == 'global' | full$Region == 'br')

ar <- subset(full, full$Region == 'ar')
at <- subset(full, full$Region == 'at')
au <- subset(full, full$Region == 'au')
be <- subset(full, full$Region == 'be')
bo <- subset(full, full$Region == 'bo')
br <- subset(full, full$Region == 'br')
ca <- subset(full, full$Region == 'ca')
ch <- subset(full, full$Region == 'ch')
cl <- subset(full, full$Region == 'cl')
co <- subset(full, full$Region == 'co')
cr <- subset(full, full$Region == 'cr')
cz <- subset(full, full$Region == 'cz')
de <- subset(full, full$Region == 'de')
dk <- subset(full, full$Region == 'dk')
do <- subset(full, full$Region == 'do')
ec <- subset(full, full$Region == 'ec')
ee <- subset(full, full$Region == 'ee')
es <- subset(full, full$Region == 'es')
fi <- subset(full, full$Region == 'fi')
fr <- subset(full, full$Region == 'fr')
gb <- subset(full, full$Region == 'gb')
global <- subset(full, full$Region == 'global')
gr <- subset(full, full$Region == 'gr')
gt <- subset(full, full$Region == 'gt')
hk <- subset(full, full$Region == 'hk')
hn <- subset(full, full$Region == 'hn')
hu <- subset(full, full$Region == 'hu')
id <- subset(full, full$Region == 'id')
ie <- subset(full, full$Region == 'ie')
is <- subset(full, full$Region == 'is')
it <- subset(full, full$Region == 'it')
jp <- subset(full, full$Region == 'jp')
lt <- subset(full, full$Region == 'lt')
lu <- subset(full, full$Region == 'lu')
lv <- subset(full, full$Region == 'lv')
mx <- subset(full, full$Region == 'mx')
my <- subset(full, full$Region == 'my')
nl <- subset(full, full$Region == 'nl')
no <- subset(full, full$Region == 'no')
nz <- subset(full, full$Region == 'nz')
pa <- subset(full, full$Region == 'pa')
pe <- subset(full, full$Region == 'pe')
ph <- subset(full, full$Region == 'ph')
pl <- subset(full, full$Region == 'pl')
pt <- subset(full, full$Region == 'pt')
py <- subset(full, full$Region == 'py')
se <- subset(full, full$Region == 'se')
sg <- subset(full, full$Region == 'sg')
sk <- subset(full, full$Region == 'sk')
sv <- subset(full, full$Region == 'sv')
tr <- subset(full, full$Region == 'tr')
tw <- subset(full, full$Region == 'tw')
us <- subset(full, full$Region == 'us')
uy <- subset(full, full$Region == 'uy')
